import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { gunzipSync } from 'node:zlib';
import { RenderError } from './render.errors';

/**
 * Emoji rendering — the answer to [Q9](../../../../docs/09-open-questions.md).
 *
 * ## The decision
 *
 * Emoji are drawn as **Twemoji SVG images**, vendored from
 * [jdecked/twemoji](https://github.com/jdecked/twemoji) and handed to Satori through its
 * `loadAdditionalAsset` hook. Nothing is fetched at render time.
 *
 * ## Why not the two easier options
 *
 * *A colour emoji font.* Satori cannot draw CBDT/sbix/COLR tables — colour emoji fonts are
 * one of its documented gaps — so the only font that works is monochrome Noto Emoji. A
 * black-and-white 🎉 on a brand-coloured card reads as a rendering bug, and small business
 * captions are full of emoji (docs/05), so it would surface on day one.
 *
 * *Fetching Twemoji from a CDN.* This is what most `@vercel/og` examples do, and it breaks
 * three things we have committed to: determinism (ADR-0002 — the same inputs must produce
 * the same bytes), the rule that `npm test` runs with no network (docs/12), and the 300ms
 * render budget, into which a cold TLS handshake does not fit.
 *
 * ## Why one gzipped bundle
 *
 * 4,009 loose SVGs is ten megabytes of files nobody will ever review. One compressed blob
 * is ~3MB, is regenerated by a script rather than edited, and changes only when the pinned
 * tag moves. It is inflated lazily — a render whose text has no emoji never touches it.
 *
 * ## Licensing
 *
 * The Twemoji graphics are CC-BY 4.0 (the code is MIT; the art is not). Attribution is in
 * `backend/assets/emoji/NOTICE.md` and docs/05. This is separate from the font licensing
 * question in Q19 and does not depend on it.
 */

/** Pinned upstream tag. Moving it is how new Unicode releases are picked up. */
export const TWEMOJI_TAG = 'v17.0.3';

export const EMOJI_ASSET_DIR = path.resolve(__dirname, '../../../assets/emoji');
export const EMOJI_BUNDLE_FILE = path.join(EMOJI_ASSET_DIR, 'twemoji.json.gz');

/**
 * Codepoints Twemoji leaves out of its filenames.
 *
 * U+FE0F is the variation selector that asks for the emoji presentation of a character
 * that also has a text form, and U+200D joins the parts of a composed emoji. Twemoji keeps
 * the joiner in its filenames but drops the variation selector, so "❤️" is `2764` and not
 * `2764-fe0f`. Getting this wrong means every emoji with a variation selector — which is
 * most of the common ones — silently misses.
 */
const VARIATION_SELECTOR_16 = 0xfe0f;

/** "👩‍💻" → `1f469-200d-1f4bb`, matching Twemoji's filenames. */
export function twemojiCodepoints(grapheme: string): string {
  return [...grapheme]
    .map((character) => character.codePointAt(0) ?? 0)
    .filter((code) => code !== VARIATION_SELECTOR_16)
    .map((code) => code.toString(16))
    .join('-');
}

let bundle: Record<string, string> | undefined;

async function loadBundle(): Promise<Record<string, string>> {
  if (bundle) return bundle;

  try {
    bundle = JSON.parse(gunzipSync(await readFile(EMOJI_BUNDLE_FILE)).toString('utf8')) as Record<
      string,
      string
    >;
    return bundle;
  } catch (cause) {
    throw new RenderError(
      'The Twemoji bundle is missing or unreadable. ' +
        'Run `npm run emoji:vendor --workspace=backend` to restore it.',
      { cause },
    );
  }
}

/**
 * The SVG for one emoji grapheme, as a data URI, or `undefined` if Twemoji has no image.
 *
 * Composed sequences degrade the way Twemoji itself does: "👩‍💻" with no composed image
 * falls back to the first codepoint's image ("👩") rather than vanishing. A woman is a
 * better answer than a hole.
 */
export async function emojiDataUri(grapheme: string): Promise<string | undefined> {
  const images = await loadBundle();
  const exact = images[twemojiCodepoints(grapheme)];
  const svg = exact ?? images[(grapheme.codePointAt(0) ?? 0).toString(16)];

  if (!svg) return undefined;

  return `data:image/svg+xml;base64,${Buffer.from(svg).toString('base64')}`;
}

/**
 * Satori's `loadAdditionalAsset` hook.
 *
 * Satori calls this with `code === 'emoji'` when it meets a grapheme none of the loaded
 * fonts covers. Returning the empty string is what makes the failure *visible*: Satori
 * draws nothing, so an emoji we have no image for leaves a gap that the caller's
 * `findUnrenderableGraphemes` check has already refused to render in the first place.
 */
export async function loadEmojiAsset(code: string, segment: string): Promise<string> {
  if (code !== 'emoji') return '';
  return (await emojiDataUri(segment)) ?? '';
}

/** Test-only. */
export function resetEmojiCacheForTests(): void {
  bundle = undefined;
}
